/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bagaturchess_nnue_NNUE_JNI_Bridge */

#ifndef _Included_bagaturchess_nnue_NNUE_JNI_Bridge
#define _Included_bagaturchess_nnue_NNUE_JNI_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bagaturchess_nnue_NNUE_JNI_Bridge
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_bagaturchess_nnue_NNUE_1JNI_1Bridge_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bagaturchess_nnue_NNUE_JNI_Bridge
 * Method:    eval
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bagaturchess_nnue_NNUE_1JNI_1Bridge_eval
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
