/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bagaturchess_nnue_v4_NNUE_Accumulator */

#ifndef _Included_bagaturchess_nnue_v4_NNUE_Accumulator
#define _Included_bagaturchess_nnue_v4_NNUE_Accumulator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
