/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bagaturchess_nnue_v4_NNUE */

#ifndef _Included_bagaturchess_nnue_v4_NNUE
#define _Included_bagaturchess_nnue_v4_NNUE
#ifdef __cplusplus
extern "C" {
#endif
#undef bagaturchess_nnue_v4_NNUE_NUM_INPUTS
#define bagaturchess_nnue_v4_NNUE_NUM_INPUTS 768L
#undef bagaturchess_nnue_v4_NNUE_L1_SIZE
#define bagaturchess_nnue_v4_NNUE_L1_SIZE 1536L
#undef bagaturchess_nnue_v4_NNUE_L2_SIZE
#define bagaturchess_nnue_v4_NNUE_L2_SIZE 8L
#undef bagaturchess_nnue_v4_NNUE_L3_SIZE
#define bagaturchess_nnue_v4_NNUE_L3_SIZE 32L
#undef bagaturchess_nnue_v4_NNUE_FT_QUANT
#define bagaturchess_nnue_v4_NNUE_FT_QUANT 255L
#undef bagaturchess_nnue_v4_NNUE_WHITE
#define bagaturchess_nnue_v4_NNUE_WHITE 0L
#undef bagaturchess_nnue_v4_NNUE_BLACK
#define bagaturchess_nnue_v4_NNUE_BLACK 1L
#undef bagaturchess_nnue_v4_NNUE_COLOR_STRIDE
#define bagaturchess_nnue_v4_NNUE_COLOR_STRIDE 384L
#undef bagaturchess_nnue_v4_NNUE_PIECE_STRIDE
#define bagaturchess_nnue_v4_NNUE_PIECE_STRIDE 64L
/*
 * Class:     bagaturchess_nnue_v4_NNUE
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_bagaturchess_nnue_1v4_NNUE_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bagaturchess_nnue_v4_NNUE
 * Method:    eval
 * Signature: ([S[SI)I
 */
JNIEXPORT jint JNICALL Java_bagaturchess_nnue_1v4_NNUE_eval
  (JNIEnv *, jclass, jshortArray, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
